import jsPDF from 'jspdf';

const W = 210;
const H = 297;
const M = 18;
const CW = W - M * 2; // 174

const C = {
  dark:   [15, 23, 42],
  card:   [30, 41, 59],
  card2:  [22, 32, 50],
  border: [51, 65, 85],
  blue:   [59, 130, 246],
  green:  [34, 197, 94],
  red:    [239, 68, 68],
  amber:  [245, 158, 11],
  purple: [139, 92, 246],
  muted:  [148, 163, 184],
  dim:    [75, 85, 99],
  white:  [241, 245, 249],
};

// ── helpers ──────────────────────────────────────────────────────────────────

function pageBase(doc) {
  doc.setFillColor(...C.dark);
  doc.rect(0, 0, W, H, 'F');
}

function pageHeader(doc, brandName, pageNum) {
  doc.setFillColor(...C.blue);
  doc.rect(0, 0, W, 12, 'F');
  doc.setFontSize(7.5);
  doc.setTextColor(255, 255, 255);
  doc.text('AEO STUDIO — AI VISIBILITY AUDIT', M, 8);
  doc.text(`${brandName}  ·  Page ${pageNum}`, W - M, 8, { align: 'right' });
}

function pageFooter(doc) {
  doc.setFillColor(...C.card);
  doc.rect(0, 287, W, 10, 'F');
  doc.setFontSize(7);
  doc.setTextColor(...C.dim);
  doc.text(
    'Generated by AEO Studio — aeo-studio.vercel.app  |  Built by Ali Hasan',
    M, 293,
  );
  doc.text(
    new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
    W - M, 293, { align: 'right' },
  );
}

function sectionHeading(doc, title, subtitle, y) {
  doc.setFontSize(12);
  doc.setTextColor(...C.white);
  doc.text(title, M, y);
  if (subtitle) {
    doc.setFontSize(7.5);
    doc.setTextColor(...C.dim);
    doc.text(subtitle, M, y + 5);
    return y + 12;
  }
  return y + 8;
}

function badge(doc, label, color, x, y) {
  const pad = 3;
  const bw = doc.getStringUnitWidth(label) * 2.65 + pad * 2;
  doc.setFillColor(...color);
  doc.roundedRect(x, y, bw, 5.5, 1, 1, 'F');
  doc.setFontSize(6);
  doc.setTextColor(0, 0, 0);
  doc.text(label, x + pad, y + 4);
  return bw;
}

// ── findings (mirrors StrategicInsights logic) ────────────────────────────────

function computeFindings(results) {
  const findings = [];
  const brandName = results.run?.brand_name || '';
  const byType = results.mentionRateByPromptType || [];
  const sov = results.competitiveShareOfVoice || [];
  const sentiment = results.sentimentByBrand || [];

  const avg = (arr) => arr.length ? arr.reduce((a, b) => a + b, 0) / arr.length : 0;

  const bnRates  = byType.filter(r => r.prompt_type === 'brand_named').map(r => r.mention_rate_pct);
  const pfRates  = byType.filter(r => r.prompt_type === 'problem_first').map(r => r.mention_rate_pct);
  const avgBN    = avg(bnRates);
  const avgPF    = avg(pfRates);
  const funnelGap = Math.round(avgBN - avgPF);

  if (funnelGap > 20) {
    findings.push({
      severity: 'critical',
      tag: 'TOP-OF-FUNNEL INVISIBILITY',
      headline: `${brandName} appears in ${Math.round(avgBN)}% of brand-named queries but only ${Math.round(avgPF)}% of problem-first — an ${funnelGap}-point gap`,
      body: 'AI systems recall this brand when a user already knows it, but fail to surface it to buyers describing a problem with no prior brand preference.',
    });
  }

  const primary = sov.find(b => b.brand === brandName);
  const topComp = sov.filter(b => b.brand !== brandName).sort((a, b) => b.pct - a.pct)[0];
  if (topComp && primary && topComp.pct > primary.pct) {
    const gap = Math.round((topComp.pct - primary.pct) * 10) / 10;
    findings.push({
      severity: gap > 15 ? 'critical' : 'warning',
      tag: 'COMPETITIVE GAP',
      headline: `${topComp.brand} leads share-of-voice by ${gap} points across ${(results.run?.total_prompts || 0)} prompts tested`,
      body: `In unaided category queries, AI systems reference ${topComp.brand} significantly more often. This is the citation gap to close.`,
    });
  }

  const pos = sentiment.find(s => s.sentiment === 'positive');
  if (pos && pos.pct >= 60) {
    findings.push({
      severity: 'positive',
      tag: 'BRAND SIGNAL STRENGTH',
      headline: `${pos.pct}% positive sentiment when mentioned — AI frames ${brandName} favorably across both models`,
      body: 'Strong sentiment when mentioned. The strategic priority is increasing mention frequency, not improving framing.',
    });
  }

  if (results.crossModelDiscrepancy?.flagged) {
    const d = results.crossModelDiscrepancy;
    findings.push({
      severity: 'warning',
      tag: 'CROSS-MODEL DISCREPANCY',
      headline: `${d.gap}-point gap between GPT-4o (${d.gpt4o?.mention_rate_pct}%) and Claude (${d.claude?.mention_rate_pct}%) — inconsistent entity recognition`,
      body: 'Large discrepancies indicate the brand entity is indexed differently across training corpora. Structured data and Wikipedia presence typically resolve this.',
    });
  }

  return findings;
}

// ── page 1: executive summary ─────────────────────────────────────────────────

function page1(doc, results) {
  pageBase(doc);
  pageHeader(doc, results.run?.brand_name || '', 1);

  const brand    = results.run?.brand_name || 'Brand';
  const category = results.run?.category || '';
  const total    = results.run?.total_prompts || 0;
  const models   = results.mentionRateByModel || [];
  const gptRate    = models.find(m => m.model === 'gpt-4o')?.mention_rate_pct ?? 0;
  const claudeRate = models.find(m => m.model === 'claude-3-5-sonnet')?.mention_rate_pct ?? 0;
  const overall    = models.length
    ? Math.round(models.reduce((s, r) => s + r.mention_rate_pct, 0) / models.length * 10) / 10
    : 0;
  const gptMentions    = models.find(m => m.model === 'gpt-4o')?.mentions ?? 0;
  const gptTotal       = models.find(m => m.model === 'gpt-4o')?.total_prompts ?? 0;
  const claudeMentions = models.find(m => m.model === 'claude-3-5-sonnet')?.mentions ?? 0;
  const claudeTotal    = models.find(m => m.model === 'claude-3-5-sonnet')?.total_prompts ?? 0;

  let y = 20;

  // Title block
  doc.setFontSize(22);
  doc.setTextColor(...C.white);
  doc.text(brand, M, y);
  y += 8;
  doc.setFontSize(9.5);
  doc.setTextColor(...C.muted);
  doc.text(`AI Visibility Audit  ·  ${category}  ·  ${total} prompts`, M, y);
  y += 11;

  doc.setDrawColor(...C.border);
  doc.setLineWidth(0.3);
  doc.line(M, y, W - M, y);
  y += 9;

  // Metric cards
  const cw3 = (CW - 6) / 3;
  const metricCards = [
    { label: 'Overall Mention Rate', value: `${overall}%`, sub: 'Across both models', color: C.blue },
    { label: 'GPT-4o Mini Rate',     value: `${gptRate}%`, sub: `${gptMentions} / ${gptTotal} prompts`, color: C.green },
    { label: 'Claude Haiku Rate',    value: `${claudeRate}%`, sub: `${claudeMentions} / ${claudeTotal} prompts`, color: C.purple },
  ];
  metricCards.forEach((card, i) => {
    const x = M + i * (cw3 + 3);
    doc.setFillColor(...C.card);
    doc.roundedRect(x, y, cw3, 24, 2, 2, 'F');
    doc.setFillColor(...card.color);
    doc.rect(x, y, cw3, 1.5, 'F');
    doc.setFontSize(19);
    doc.setTextColor(...card.color);
    doc.text(card.value, x + cw3 / 2, y + 13, { align: 'center' });
    doc.setFontSize(7.5);
    doc.setTextColor(...C.white);
    doc.text(card.label, x + cw3 / 2, y + 19, { align: 'center' });
    doc.setFontSize(6.5);
    doc.setTextColor(...C.dim);
    doc.text(card.sub, x + cw3 / 2, y + 23, { align: 'center' });
  });
  y += 30;

  // Strategic findings
  const findings = computeFindings(results);
  doc.setFontSize(11);
  doc.setTextColor(...C.white);
  doc.text('Strategic Findings', M, y);
  doc.setFontSize(7.5);
  doc.setTextColor(...C.dim);
  doc.text(`${findings.length} findings  ·  ${total} prompts  ·  2 models`, M + 35, y);
  y += 7;

  findings.slice(0, 3).forEach((f, i) => {
    const sevColor = f.severity === 'critical' ? C.red : f.severity === 'warning' ? C.amber : C.green;
    const sevBg    = f.severity === 'critical' ? [42,15,15] : f.severity === 'warning' ? [42,32,8] : [12,36,18];

    const headLines = doc.splitTextToSize(f.headline, CW - 18);
    const cardH = Math.min(headLines.length * 5 + 20, 35);

    doc.setFillColor(...sevBg);
    doc.roundedRect(M, y, CW, cardH, 2, 2, 'F');
    doc.setDrawColor(...sevColor);
    doc.setLineWidth(0.25);
    doc.roundedRect(M, y, CW, cardH, 2, 2, 'S');

    // Number badge
    doc.setFillColor(...sevColor);
    doc.roundedRect(M + 3, y + 4, 7, 7, 1, 1, 'F');
    doc.setFontSize(7);
    doc.setTextColor(0, 0, 0);
    doc.text(`0${i + 1}`, M + 6.5, y + 9.3, { align: 'center' });

    // Tag
    doc.setFontSize(6.5);
    doc.setTextColor(...sevColor);
    doc.text(`${f.tag}  ·  ${f.severity.toUpperCase()}`, M + 13, y + 8);

    // Headline
    doc.setFontSize(8);
    doc.setTextColor(...C.white);
    headLines.slice(0, 3).forEach((line, li) => {
      doc.text(line, M + 13, y + 14 + li * 5);
    });

    y += cardH + 4;
  });

  y += 3;

  // Competitive Share of Voice
  const sov = results.competitiveShareOfVoice || [];
  if (sov.length && y < 250) {
    y = sectionHeading(doc, 'Competitive Share of Voice', null, y);
    const maxPct   = Math.max(...sov.map(b => b.pct), 1);
    const barMaxW  = CW - 52;

    sov.forEach(brand => {
      const isPrimary = brand.brand === results.run?.brand_name;
      const barW = Math.max((brand.pct / maxPct) * barMaxW, 1);

      doc.setFontSize(9);
      doc.setTextColor(isPrimary ? C.white[0] : C.muted[0], isPrimary ? C.white[1] : C.muted[1], isPrimary ? C.white[2] : C.muted[2]);
      doc.text(brand.brand, M, y + 5);
      if (isPrimary) {
        doc.setFontSize(6.5);
        doc.setTextColor(...C.blue);
        doc.text('you', M + doc.getTextWidth(brand.brand) + 2, y + 5);
      }

      doc.setFillColor(...C.card);
      doc.roundedRect(M + 37, y, barMaxW, 7, 1, 1, 'F');
      doc.setFillColor(...(isPrimary ? C.blue : [107, 114, 128]));
      doc.roundedRect(M + 37, y, barW, 7, 1, 1, 'F');

      doc.setFontSize(8.5);
      doc.setTextColor(...C.white);
      doc.text(`${brand.pct}%`, M + 37 + barMaxW + 3, y + 5.5);
      y += 11;
    });
  }

  pageFooter(doc);
}

// ── page 2: visibility breakdown ─────────────────────────────────────────────

function page2(doc, results) {
  doc.addPage();
  pageBase(doc);
  pageHeader(doc, results.run?.brand_name || '', 2);

  let y = 20;

  y = sectionHeading(
    doc,
    'Mention Rate by Prompt Type',
    'Brand-named prompts represent aided recall; category-general and problem-first reveal organic discovery gaps',
    y,
  );

  const byType = results.mentionRateByPromptType || [];
  const promptTypes = [
    { key: 'brand_named',           label: 'Brand Named',           color: C.blue },
    { key: 'category_general',      label: 'Category General',      color: C.purple },
    { key: 'competitor_comparison',  label: 'Competitor Comparison', color: C.amber },
    { key: 'problem_first',         label: 'Problem First',         color: C.green },
  ];

  // Table header
  doc.setFillColor(...C.card);
  doc.rect(M, y, CW, 8, 'F');
  doc.setFontSize(7.5);
  doc.setTextColor(...C.muted);
  doc.text('Prompt Type',    M + 6, y + 5.5);
  doc.text('GPT-4o Mini',   M + 85, y + 5.5);
  doc.text('Claude Haiku',  M + 115, y + 5.5);
  doc.text('Overall',       M + 149, y + 5.5);
  y += 8;

  promptTypes.forEach((pt, idx) => {
    const gptR    = byType.find(r => r.prompt_type === pt.key && r.model === 'gpt-4o')?.mention_rate_pct ?? 0;
    const claudeR = byType.find(r => r.prompt_type === pt.key && r.model === 'claude-3-5-sonnet')?.mention_rate_pct ?? 0;
    const overall = Math.round((gptR + claudeR) / 2 * 10) / 10;

    const rowH = 13;
    const bg = idx % 2 === 0 ? C.card2 : [26, 36, 54];
    doc.setFillColor(...bg);
    doc.rect(M, y, CW, rowH, 'F');

    doc.setFillColor(...pt.color);
    doc.rect(M, y, 2.5, rowH, 'F');

    doc.setFontSize(8.5);
    doc.setTextColor(...C.white);
    doc.text(pt.label, M + 6, y + 8);

    // Mini bar + value for GPT
    const gptBW = Math.min((gptR / 100) * 20, 20);
    doc.setFillColor(...C.card);
    doc.roundedRect(M + 83, y + 3, 20, 5, 0.5, 0.5, 'F');
    doc.setFillColor(...C.green);
    if (gptBW > 0) doc.roundedRect(M + 83, y + 3, gptBW, 5, 0.5, 0.5, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...C.white);
    doc.text(`${gptR}%`, M + 105, y + 8);

    // Mini bar + value for Claude
    const claudeBW = Math.min((claudeR / 100) * 20, 20);
    doc.setFillColor(...C.card);
    doc.roundedRect(M + 113, y + 3, 20, 5, 0.5, 0.5, 'F');
    doc.setFillColor(...C.purple);
    if (claudeBW > 0) doc.roundedRect(M + 113, y + 3, claudeBW, 5, 0.5, 0.5, 'F');
    doc.text(`${claudeR}%`, M + 135, y + 8);

    // Overall — colored by performance
    const perfColor = overall >= 50 ? C.green : overall >= 25 ? C.amber : C.red;
    doc.setFontSize(9);
    doc.setTextColor(...perfColor);
    doc.text(`${overall}%`, M + 150, y + 8);

    y += rowH;
  });

  y += 14;

  // Co-mention matrix
  const coMatrix = results.coMentionMatrix || [];
  if (coMatrix.length) {
    y = sectionHeading(
      doc,
      'Co-Mention Matrix',
      `When AI mentions a competitor, how often does it also mention ${results.run?.brand_name}?`,
      y,
    );

    doc.setFillColor(...C.card);
    doc.rect(M, y, CW, 8, 'F');
    doc.setFontSize(7.5);
    doc.setTextColor(...C.muted);
    doc.text('When AI mentions...', M + 6, y + 5.5);
    doc.text('GPT-4o Mini',        M + 85, y + 5.5);
    doc.text('Claude Haiku',       M + 115, y + 5.5);
    doc.text('Overall',            M + 149, y + 5.5);
    y += 8;

    coMatrix.forEach((row, idx) => {
      const rowH = 14;
      const bg = idx % 2 === 0 ? C.card2 : [26, 36, 54];
      doc.setFillColor(...bg);
      doc.rect(M, y, CW, rowH, 'F');

      doc.setFontSize(8.5);
      doc.setTextColor(...C.white);
      doc.text(row.competitor, M + 6, y + 6);
      doc.setFontSize(7);
      doc.setTextColor(...C.dim);
      doc.text(`also mentions ${results.run?.brand_name}...`, M + 6, y + 11);

      const gptPct    = row.byModel?.find(m => m.model === 'gpt-4o')?.pct ?? row.pct;
      const claudePct = row.byModel?.find(m => m.model === 'claude-3-5-sonnet')?.pct ?? row.pct;

      doc.setFontSize(9);
      doc.setTextColor(...C.green);
      doc.text(`${Math.round(gptPct)}%`, M + 87, y + 8.5);
      doc.setTextColor(...C.purple);
      doc.text(`${Math.round(claudePct)}%`, M + 117, y + 8.5);
      doc.setTextColor(...C.white);
      doc.text(`${Math.round(row.pct)}%`, M + 151, y + 8.5);

      y += rowH;
    });
  }

  pageFooter(doc);
}

// ── page 3: sentiment & evidence ─────────────────────────────────────────────

function page3(doc, results) {
  doc.addPage();
  pageBase(doc);
  pageHeader(doc, results.run?.brand_name || '', 3);

  let y = 20;

  y = sectionHeading(doc, 'Sentiment Analysis', null, y);

  const sentiment = results.sentimentByBrand || [];
  const sentMap = Object.fromEntries(sentiment.map(s => [s.sentiment, s]));

  // Sentiment metric cards
  const sCW = (CW - 6) / 3;
  const sCards = [
    { label: 'Positive Sentiment', value: `${sentMap.positive?.pct || 0}%`, sub: `${sentMap.positive?.count || 0} responses`, color: C.green },
    { label: 'Neutral Sentiment',  value: `${sentMap.neutral?.pct || 0}%`,  sub: `${sentMap.neutral?.count || 0} responses`,  color: C.muted },
    { label: 'Negative Sentiment', value: `${sentMap.negative?.pct || 0}%`, sub: `${sentMap.negative?.count || 0} responses`, color: C.red },
  ];
  sCards.forEach((card, i) => {
    const x = M + i * (sCW + 3);
    doc.setFillColor(...C.card);
    doc.roundedRect(x, y, sCW, 22, 2, 2, 'F');
    doc.setFillColor(...card.color);
    doc.rect(x, y, sCW, 1.5, 'F');
    doc.setFontSize(18);
    doc.setTextColor(...card.color);
    doc.text(card.value, x + sCW / 2, y + 12, { align: 'center' });
    doc.setFontSize(7.5);
    doc.setTextColor(...C.white);
    doc.text(card.label, x + sCW / 2, y + 17.5, { align: 'center' });
    doc.setFontSize(6.5);
    doc.setTextColor(...C.dim);
    doc.text(card.sub, x + sCW / 2, y + 21.5, { align: 'center' });
  });
  y += 27;

  // Stacked sentiment bar
  const sentColors = { positive: C.green, neutral: C.muted, negative: C.red };
  let barX = M;
  ['negative', 'neutral', 'positive'].forEach(k => {
    const s = sentMap[k];
    if (!s) return;
    const bw = (s.pct / 100) * CW;
    doc.setFillColor(...sentColors[k]);
    doc.rect(barX, y, Math.max(bw - 0.5, 0.5), 7, 'F');
    barX += bw;
  });
  y += 9;
  let legendX = M;
  ['negative', 'neutral', 'positive'].forEach(k => {
    const s = sentMap[k];
    if (!s) return;
    doc.setFillColor(...sentColors[k]);
    doc.rect(legendX, y - 1, 3, 3, 'F');
    doc.setFontSize(7.5);
    doc.setTextColor(...C.muted);
    const lbl = `${k.charAt(0).toUpperCase() + k.slice(1)}: ${s.pct}%`;
    doc.text(lbl, legendX + 5, y + 2);
    legendX += doc.getTextWidth(lbl) + 16;
  });
  y += 12;

  // Representative positive responses
  const responses = (results.sampleResponses || [])
    .filter(r => r.brand_mentioned === 1)
    .sort((a, b) => (b.sentiment === 'positive' ? 1 : 0) - (a.sentiment === 'positive' ? 1 : 0))
    .slice(0, 3);

  if (responses.length) {
    y = sectionHeading(doc, 'Representative AI Responses', `Responses where ${results.run?.brand_name} was mentioned`, y);

    responses.forEach(resp => {
      if (y > 268) return;

      const modelLabel = resp.model === 'gpt-4o' ? 'GPT-4o Mini' : resp.model === 'claude-3-5-sonnet' ? 'Claude Haiku' : resp.model;
      const modelColor = resp.model === 'gpt-4o' ? C.green : C.purple;
      const sentBadgeColor = resp.sentiment === 'positive' ? C.green : resp.sentiment === 'negative' ? C.red : C.muted;

      const excerpt = (resp.response_text || '').slice(0, 320) + ((resp.response_text || '').length > 320 ? '…' : '');
      const excerptLines = doc.splitTextToSize(excerpt, CW - 10);
      const cardH = Math.min(excerptLines.length * 4.3 + 18, 48);

      doc.setFillColor(...C.card);
      doc.roundedRect(M, y, CW, cardH, 2, 2, 'F');
      doc.setDrawColor(...C.border);
      doc.setLineWidth(0.2);
      doc.roundedRect(M, y, CW, cardH, 2, 2, 'S');

      // Left accent by sentiment
      doc.setFillColor(...sentBadgeColor);
      doc.rect(M, y, 2, cardH, 'F');

      // Model badge
      const mbW = badge(doc, modelLabel, modelColor, M + 5, y + 3);

      // Sentiment badge
      badge(doc, resp.sentiment || 'neutral', sentBadgeColor, M + 5 + mbW + 2, y + 3);

      // Prompt text
      doc.setFontSize(7);
      doc.setTextColor(...C.dim);
      const promptSnip = (resp.prompt_text || '').slice(0, 80) + ((resp.prompt_text || '').length > 80 ? '…' : '');
      doc.text(`"${promptSnip}"`, M + 5, y + 13);

      // Response excerpt
      doc.setFontSize(7.5);
      doc.setTextColor(...C.muted);
      excerptLines.slice(0, Math.floor((cardH - 16) / 4.3)).forEach((line, li) => {
        doc.text(line, M + 5, y + 17 + li * 4.3);
      });

      y += cardH + 4;
    });
  }

  pageFooter(doc);
}

// ── page 4: recommendations ───────────────────────────────────────────────────

function page4(doc, results) {
  doc.addPage();
  pageBase(doc);
  pageHeader(doc, results.run?.brand_name || '', 4);

  const brand  = results.run?.brand_name || 'Brand';
  const byType = results.mentionRateByPromptType || [];
  const pfRates = byType.filter(r => r.prompt_type === 'problem_first').map(r => r.mention_rate_pct);
  const pfAvg   = pfRates.length ? Math.round(pfRates.reduce((a, b) => a + b, 0) / pfRates.length) : 0;

  let y = 20;

  y = sectionHeading(
    doc,
    'AEO Improvement Recommendations',
    'Concrete actions to improve AI visibility, ordered by expected impact',
    y,
  );

  const sections = [
    {
      priority: 'HIGH', color: C.red,
      title: 'Structured Data',
      items: [
        `Add Organization schema with sameAs links to Wikipedia, Crunchbase, LinkedIn — ${brand}'s entity graph needs authoritative anchors`,
        'Add Product schema with complete pricing, features, and review aggregates so AI can cite specific attributes',
        'Ensure FAQPage schema covers your most common brand-named prompt questions',
      ],
    },
    {
      priority: 'HIGH', color: C.red,
      title: 'Citation Authority',
      items: [
        'Get listed in authoritative industry directories (G2, Capterra, TechCrunch) — these are heavily indexed by all major LLMs',
        'Build Wikipedia presence — models assign disproportionate weight to Wikipedia citations in brand entity resolution',
        'Earn bylines in sources LLMs frequently cite (Forbes, WSJ, Wired for your category)',
      ],
    },
    {
      priority: 'MEDIUM', color: C.amber,
      title: 'Problem-First Content',
      items: [
        `Current problem-first mention rate is ${pfAvg}% — create content anchored to the specific pain queries buyers use before they know your brand`,
        'Publish problem-framed content from authoritative third-party sources (Reddit, G2 reviews, analyst briefings)',
        'Case studies with quantified outcomes get cited disproportionately in problem-first AI responses',
      ],
    },
    {
      priority: 'MEDIUM', color: C.amber,
      title: 'Consistent Brand Entity',
      items: [
        `Use identical brand name spelling across all properties — variations create entity fragmentation in LLM training data`,
        'Maintain consistent category language between site copy, G2 categories, and third-party listings',
        'Ensure your brand description is factually consistent across Wikipedia, Crunchbase, and LinkedIn',
      ],
    },
    {
      priority: 'LOW NOW / CRITICAL 2027', color: C.dim,
      title: 'Agent Readiness',
      items: [
        'Expose pricing as machine-readable JSON — not buried in PDFs or "contact us" flows that agents cannot parse',
        'Implement API-accessible feature availability and integration lists for autonomous procurement agents',
        'Build or partner with checkout APIs that AI agents can trigger without human intervention',
      ],
    },
  ];

  sections.forEach(section => {
    const itemLineCount = section.items.reduce((acc, item) => {
      return acc + doc.splitTextToSize(item, CW - 14).length;
    }, 0);
    const sH = itemLineCount * 4.2 + 16;
    if (y + sH > 280) return;

    doc.setFillColor(...C.card);
    doc.roundedRect(M, y, CW, sH, 2, 2, 'F');

    // Priority badge
    const bW = badge(doc, section.priority, section.color, M + 3, y + 4);

    // Section title
    doc.setFontSize(9.5);
    doc.setTextColor(...C.white);
    doc.text(section.title, M + bW + 7, y + 8.5);

    let itemY = y + 15;
    section.items.forEach(item => {
      const lines = doc.splitTextToSize(item, CW - 14);
      doc.setFillColor(...C.amber);
      doc.circle(M + 5, itemY - 0.5, 0.8, 'F');
      doc.setFontSize(7.5);
      doc.setTextColor(...C.muted);
      lines.forEach((line, li) => {
        doc.text(line, M + 9, itemY + li * 4.2);
      });
      itemY += lines.length * 4.2 + 2;
    });

    y += sH + 5;
  });

  pageFooter(doc);
}

// ── main export ───────────────────────────────────────────────────────────────

export async function generateAuditPDF(results) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  page1(doc, results);
  page2(doc, results);
  page3(doc, results);
  page4(doc, results);

  const brand    = (results.run?.brand_name || 'Brand').replace(/\s+/g, '_');
  const dateStr  = new Date().toISOString().slice(0, 10);
  doc.save(`${brand}_AI_Visibility_Audit_${dateStr}.pdf`);
}
